-- Catálogo de distritos/municipios del Paraguay basado en INE CNPV 2022.
INSERT INTO cities (city_name)
VALUES
  ('No definido'),
  ('25 De Diciembre'),
  ('3 De Febrero'),
  ('3 De Mayo'),
  ('Abai'),
  ('Acahay'),
  ('Alberdi'),
  ('Alto Vera'),
  ('Altos'),
  ('Antequera'),
  ('Aregua'),
  ('Arroyito'),
  ('Arroyos Y Esteros'),
  ('Asuncion'),
  ('Atyra'),
  ('Ayolas'),
  ('Azote''y'),
  ('Bahia Negra'),
  ('Belen'),
  ('Bella Vista'),
  ('Benjamin Aceval'),
  ('Boqueron'),
  ('Borja'),
  ('Buena Vista'),
  ('Caacupe'),
  ('Caaguazu'),
  ('Caapucu'),
  ('Caazapa'),
  ('Caballero'),
  ('Cambyreta'),
  ('Campo Aceval'),
  ('Capiata'),
  ('Capiibary'),
  ('Capitan Bado'),
  ('Capitan Mauricio Jose Troche'),
  ('Capitan Meza'),
  ('Capitan Miranda'),
  ('Caraguatay'),
  ('Carapegua'),
  ('Carayao'),
  ('Carlos Antonio Lopez'),
  ('Carmelo Peralta'),
  ('Carmen Del Parana'),
  ('Cerrito'),
  ('Cerro Cora'),
  ('Chore'),
  ('Ciudad Del Este'),
  ('Colonia Independencia'),
  ('Concepcion'),
  ('Coronel Bogado'),
  ('Coronel Martinez'),
  ('Coronel Oviedo'),
  ('Corpus Christi'),
  ('Desmochados'),
  ('Doctor Bottrell'),
  ('Domingo Martinez De Irala'),
  ('Dr. Cecilio Baez'),
  ('Dr. J. Eulogio Estigarribia'),
  ('Dr. Juan Leon Mallorquin'),
  ('Dr. Juan Manuel Frutos'),
  ('Dr. Moises S. Bertoni'),
  ('Dr. Raul Peña'),
  ('Edelira'),
  ('Emboscada'),
  ('Encarnacion'),
  ('Escobar'),
  ('Eusebio Ayala'),
  ('Felix Perez Cardozo'),
  ('Fernando De La Mora'),
  ('Filadelfia'),
  ('Fram'),
  ('Francisco Caballero Alvarez'),
  ('Fuerte Olimpo'),
  ('General Artigas'),
  ('General Delgado'),
  ('General Elizardo Aquino'),
  ('General Francisco Isidoro Resquin'),
  ('General Jose Maria Bruguez'),
  ('Gral. Eugenio A. Garay'),
  ('Gral. Higinio Morinigo'),
  ('Gral. Jose Eduvigis Diaz'),
  ('Guajayvi'),
  ('Guarambare'),
  ('Guazu Cua'),
  ('Hernandarias'),
  ('Hohenau'),
  ('Horqueta'),
  ('Humaita'),
  ('Iruña'),
  ('Isla Pucu'),
  ('Isla Umbu'),
  ('Ita'),
  ('Itacua'),
  ('Itacurubi De La Cordillera'),
  ('Itacurubi Del Rosario'),
  ('Itakyry'),
  ('Itanara'),
  ('Itape'),
  ('Itapua Poty'),
  ('Itaugua'),
  ('Iturbe'),
  ('J. Augusto Saldivar'),
  ('Jesus'),
  ('Jose Domingo Ocampos'),
  ('Jose Falcon'),
  ('Jose Fassardi'),
  ('Jose Leandro Oviedo'),
  ('Juan De Mena'),
  ('Juan E. O''leary'),
  ('Karapai'),
  ('Katuete'),
  ('La Colmena'),
  ('La Paloma Del Espiritu Santo'),
  ('La Pastora'),
  ('La Paz'),
  ('Lambare'),
  ('Laurel'),
  ('Laureles'),
  ('Liberacion'),
  ('Lima'),
  ('Limpio'),
  ('Loma Grande'),
  ('Loma Plata'),
  ('Loreto'),
  ('Los Cedrales'),
  ('Luque'),
  ('Maciel'),
  ('Maracana'),
  ('Maria Antonia'),
  ('Mariano Roque Alonso'),
  ('Mariscal Francisco Solano Lopez'),
  ('Mariscal Jose Felix Estigarribia'),
  ('Mayor Jose De Jesus Martinez'),
  ('Mayor Julio Dionisio Otaño'),
  ('Mbaracayu'),
  ('Mbocayaty'),
  ('Mbocayaty Del Yhaguy'),
  ('Mbuyapey'),
  ('Minga Guazu'),
  ('Minga Pora'),
  ('Nanawa'),
  ('Naranjal'),
  ('Natalicio Talavera'),
  ('Natalio'),
  ('Nueva Alborada'),
  ('Nueva Asuncion'),
  ('Nueva Colombia'),
  ('Nueva Esperanza'),
  ('Nueva Germania'),
  ('Nueva Italia'),
  ('Nueva Londres'),
  ('Nueva Toledo'),
  ('Ñacunday'),
  ('Ñemby'),
  ('Ñumi'),
  ('Obligado'),
  ('Paraguari'),
  ('Paso Barreto'),
  ('Paso De Patria'),
  ('Paso Horqueta'),
  ('Paso Yobai'),
  ('Pedro Juan Caballero'),
  ('Pilar'),
  ('Pirapo'),
  ('Pirayu'),
  ('Piribebuy'),
  ('Presidente Franco'),
  ('Primero De Marzo'),
  ('Puerto Adela'),
  ('Puerto Casado'),
  ('Puerto Pinasco'),
  ('Quiindy'),
  ('Quyquyho'),
  ('R.I. 3 Corrales'),
  ('Raul Arsenio Oviedo'),
  ('Repatriacion'),
  ('Roque Gonzalez De Santa Cruz'),
  ('Salto Del Guaira'),
  ('San Alberto'),
  ('San Alfredo'),
  ('San Antonio'),
  ('San Bernardino'),
  ('San Carlos Del Apa'),
  ('San Cosme Y Damian'),
  ('San Cristobal'),
  ('San Estanislao'),
  ('San Ignacio'),
  ('San Joaquin'),
  ('San Jose De Los Arroyos'),
  ('San Jose Del Rosario'),
  ('San Jose Obrero'),
  ('San Juan Bautista De Las Misiones'),
  ('San Juan Bautista De Ñeembucu'),
  ('San Juan Del Parana'),
  ('San Juan Nepomuceno'),
  ('San Lazaro'),
  ('San Lorenzo'),
  ('San Miguel'),
  ('San Pablo'),
  ('San Patricio'),
  ('San Pedro Del Parana'),
  ('San Pedro Del Ycuamandyyu'),
  ('San Rafael Del Parana'),
  ('San Salvador'),
  ('San Vicente Pancholo'),
  ('Santa Elena'),
  ('Santa Fe Del Parana'),
  ('Santa Maria'),
  ('Santa Rita'),
  ('Santa Rosa'),
  ('Santa Rosa Del Aguaray'),
  ('Santa Rosa Del Mbutuy'),
  ('Santa Rosa Del Monday'),
  ('Santiago'),
  ('Sapucai'),
  ('Sargento Jose Felix Lopez'),
  ('Simon Bolivar'),
  ('Tacuaras'),
  ('Tacuati'),
  ('Tavai'),
  ('Tavapy'),
  ('Tebicuary'),
  ('Tebicuary-Mi'),
  ('Tembiapora'),
  ('Teniente Esteban Martinez'),
  ('Tobati'),
  ('Tomas Romero Pereira'),
  ('Trinidad'),
  ('Tte 1Ro Manuel Irala Fernandez'),
  ('Union'),
  ('Valenzuela'),
  ('Vaqueria'),
  ('Villa Curuguaty'),
  ('Villa Del Rosario'),
  ('Villa Elisa'),
  ('Villa Florida'),
  ('Villa Franca'),
  ('Villa Hayes'),
  ('Villa Oliva'),
  ('Villa Ygatimi'),
  ('Villalbin'),
  ('Villarrica'),
  ('Villeta'),
  ('Yabebyry'),
  ('Yaguaron'),
  ('Yasy Kañy'),
  ('Yataity'),
  ('Yataity Del Norte'),
  ('Yatytay'),
  ('Yby Pyta'),
  ('Yby Yau'),
  ('Ybycui'),
  ('Ybyrarobana'),
  ('Ybytymi'),
  ('Yegros'),
  ('Yguazu'),
  ('Yhu'),
  ('Ypacarai'),
  ('Ypane'),
  ('Ypejhu'),
  ('Yrybucua'),
  ('Yuty'),
  ('Zanja Pyta')
ON CONFLICT (city_name) DO NOTHING;
