-- ============================================================
-- BoviTrans MVP — Database Initialization Script
-- PostgreSQL 16
-- Idempotente: usa IF NOT EXISTS y ON CONFLICT DO NOTHING
-- ============================================================

CREATE EXTENSION IF NOT EXISTS pgcrypto;

-- ─────────────────────────────────────────
-- TIPOS ENUM
-- ─────────────────────────────────────────

DO $$ BEGIN
  CREATE TYPE truck_status AS ENUM ('available', 'assigned', 'maintenance');
EXCEPTION WHEN duplicate_object THEN NULL;
END $$;

DO $$ BEGIN
  CREATE TYPE request_status AS ENUM ('pending', 'assigned', 'confirmed', 'in_progress', 'completed', 'cancelled');
EXCEPTION WHEN duplicate_object THEN NULL;
END $$;

ALTER TYPE request_status ADD VALUE IF NOT EXISTS 'confirmed' AFTER 'assigned';

-- ─────────────────────────────────────────
-- TABLA: trucks
-- ─────────────────────────────────────────

CREATE TABLE IF NOT EXISTS trucks (
  id                      UUID          PRIMARY KEY DEFAULT gen_random_uuid(),
  license_plate           VARCHAR(20)   NOT NULL,
  brand                   VARCHAR(80)   NOT NULL DEFAULT 'Genérico',
  model                   VARCHAR(120)  NOT NULL DEFAULT 'Camión ganadero',
  engine_power_hp         INTEGER       NULL,
  tare_weight_tons        DECIMAL(6,2)  NOT NULL DEFAULT 9.00,
  empty_fuel_consumption_per_km DECIMAL(7,4) NOT NULL DEFAULT 0.3200,
  fuel_consumption_per_ton_km DECIMAL(7,4) NOT NULL DEFAULT 0.0065,
  max_capacity            INTEGER       NOT NULL,
  vehicle_configuration   VARCHAR(40)   NOT NULL DEFAULT 'truck_semitrailer',
  axle_configuration      VARCHAR(40)   NOT NULL DEFAULT 'double_dual',
  length_m                DECIMAL(5,2)  NOT NULL DEFAULT 22.40,
  max_weight_tons         DECIMAL(6,2)  NOT NULL DEFAULT 18.00,
  reference_cattle_weight_kg INTEGER     NOT NULL DEFAULT 450,
  fuel_consumption_per_km DECIMAL(6,3)  NOT NULL,
  status                  truck_status  NOT NULL DEFAULT 'available',
  created_at              TIMESTAMPTZ   NOT NULL DEFAULT NOW(),
  updated_at              TIMESTAMPTZ   NOT NULL DEFAULT NOW(),

  CONSTRAINT trucks_license_plate_unique   UNIQUE (license_plate),
  CONSTRAINT trucks_engine_power_positive CHECK (engine_power_hp IS NULL OR engine_power_hp > 0),
  CONSTRAINT trucks_tare_weight_positive CHECK (tare_weight_tons > 0),
  CONSTRAINT trucks_empty_fuel_positive CHECK (empty_fuel_consumption_per_km > 0),
  CONSTRAINT trucks_fuel_ton_positive CHECK (fuel_consumption_per_ton_km > 0),
  CONSTRAINT trucks_max_capacity_positive  CHECK  (max_capacity > 0),
  CONSTRAINT trucks_length_positive CHECK (length_m > 0),
  CONSTRAINT trucks_max_weight_positive CHECK (max_weight_tons > 0),
  CONSTRAINT trucks_reference_cattle_weight_positive CHECK (reference_cattle_weight_kg > 0),
  CONSTRAINT trucks_vehicle_configuration_check CHECK (
    vehicle_configuration IN (
      'simple_truck', 'truck_with_trailer', 'trailer',
      'truck_semitrailer', 'truck_semitrailer_trailer'
    )
  ),
  CONSTRAINT trucks_axle_configuration_check CHECK (
    axle_configuration IN (
      'single_single', 'single_dual', 'double_single',
      'double_dual_single', 'double_dual',
      'triple_dual_single', 'triple_dual'
    )
  ),
  CONSTRAINT trucks_fuel_consumption_positive CHECK (fuel_consumption_per_km > 0)
);

-- Índices
CREATE INDEX IF NOT EXISTS idx_trucks_status        ON trucks (status);
CREATE INDEX IF NOT EXISTS idx_trucks_license_plate ON trucks (license_plate);

CREATE TABLE IF NOT EXISTS app_users (
  id            UUID         PRIMARY KEY DEFAULT gen_random_uuid(),
  username      VARCHAR(60)  NOT NULL UNIQUE,
  email         VARCHAR(254) NOT NULL UNIQUE,
  full_name     VARCHAR(120) NOT NULL,
  password_hash TEXT         NOT NULL,
  superuser     BOOLEAN      NOT NULL DEFAULT FALSE,
  active        BOOLEAN      NOT NULL DEFAULT TRUE,
  created_at    TIMESTAMPTZ  NOT NULL DEFAULT NOW(),
  updated_at    TIMESTAMPTZ  NOT NULL DEFAULT NOW()
);

CREATE TABLE IF NOT EXISTS app_user_permissions (
  user_id    UUID        NOT NULL REFERENCES app_users(id) ON DELETE CASCADE,
  module_key VARCHAR(40) NOT NULL,
  created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  CONSTRAINT app_user_permissions_pk PRIMARY KEY (user_id, module_key),
  CONSTRAINT app_user_permissions_module_check CHECK (module_key IN ('logistics', 'fleet', 'users'))
);

CREATE INDEX IF NOT EXISTS idx_app_users_username ON app_users (username);
CREATE INDEX IF NOT EXISTS idx_app_users_email ON app_users (email);

CREATE TABLE IF NOT EXISTS document_types (
  id            INTEGER      GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  document_type VARCHAR(20)  NOT NULL UNIQUE
);

INSERT INTO document_types (id, document_type)
VALUES (1, 'RUC'), (2, 'CI')
ON CONFLICT DO NOTHING;

CREATE TABLE IF NOT EXISTS cities (
  id        INTEGER      GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  city_name VARCHAR(160) NOT NULL UNIQUE
);

INSERT INTO cities (id, city_name)
VALUES (1, 'No definido')
ON CONFLICT DO NOTHING;

CREATE TABLE IF NOT EXISTS clients (
  id               UUID         PRIMARY KEY DEFAULT gen_random_uuid(),
  company_name     VARCHAR(160) NOT NULL,
  business_name    VARCHAR(160) NOT NULL,
  document_number  VARCHAR(40)  NOT NULL,
  document_type_id INTEGER      NOT NULL REFERENCES document_types(id),
  phone_number     VARCHAR(40)  NOT NULL,
  city_id          INTEGER      NOT NULL DEFAULT 1 REFERENCES cities(id),
  email            VARCHAR(254) NULL,
  created_at       TIMESTAMPTZ  NOT NULL DEFAULT NOW(),
  updated_at       TIMESTAMPTZ  NOT NULL DEFAULT NOW(),
  CONSTRAINT clients_document_unique UNIQUE (document_type_id, document_number)
);

CREATE INDEX IF NOT EXISTS idx_clients_company_name ON clients (company_name);
CREATE INDEX IF NOT EXISTS idx_clients_business_name ON clients (business_name);
CREATE INDEX IF NOT EXISTS idx_clients_document_number ON clients (document_number);

-- ─────────────────────────────────────────
-- TABLA: transport_requests
-- ─────────────────────────────────────────

CREATE TABLE IF NOT EXISTS transport_requests (
  id               UUID            PRIMARY KEY DEFAULT gen_random_uuid(),

  -- Datos del cliente
  client_id        UUID            NULL
                   REFERENCES clients(id)
                   ON DELETE RESTRICT
                   ON UPDATE CASCADE,
  client_name      VARCHAR(120)    NOT NULL,
  cattle_count     INTEGER         NOT NULL,
  cattle_weight_min_kg INTEGER     NOT NULL DEFAULT 400,
  cattle_weight_max_kg INTEGER     NOT NULL DEFAULT 500,

  -- Origen
  origin_name      VARCHAR(200)    NOT NULL,
  origin_lat       DECIMAL(10,7)   NOT NULL,
  origin_lng       DECIMAL(10,7)   NOT NULL,

  -- Destino
  destination_name VARCHAR(200)    NOT NULL,
  destination_lat  DECIMAL(10,7)   NOT NULL,
  destination_lng  DECIMAL(10,7)   NOT NULL,

  -- Logística calculada (se persiste al asignar camión)
  distance_km      DECIMAL(10,3)   NULL,
  fuel_cost        DECIMAL(12,2)   NULL,
  fuel_price_id    UUID            NULL,
  trips_needed     INTEGER         NULL DEFAULT 1,
  departure_at     TIMESTAMPTZ     NULL,
  estimated_arrival_at TIMESTAMPTZ NULL,

  -- Relaciones y estado
  status           request_status  NOT NULL DEFAULT 'pending',
  truck_id         UUID            NULL
                   REFERENCES trucks(id)
                   ON DELETE RESTRICT
                   ON UPDATE CASCADE,

  notes            TEXT            NULL,
  source           VARCHAR(20)     NOT NULL DEFAULT 'internal',
  route_pending    BOOLEAN         NOT NULL DEFAULT FALSE,
  created_at       TIMESTAMPTZ     NOT NULL DEFAULT NOW(),
  updated_at       TIMESTAMPTZ     NOT NULL DEFAULT NOW(),

  CONSTRAINT tr_cattle_count_positive CHECK (cattle_count > 0),
  CONSTRAINT tr_cattle_weight_min_positive CHECK (cattle_weight_min_kg > 0),
  CONSTRAINT tr_cattle_weight_max_positive CHECK (cattle_weight_max_kg > 0),
  CONSTRAINT tr_cattle_weight_range_valid CHECK (cattle_weight_min_kg <= cattle_weight_max_kg),
  CONSTRAINT tr_trips_needed_positive CHECK (trips_needed > 0),
  CONSTRAINT tr_origin_dest_different CHECK (
    origin_lat <> destination_lat OR origin_lng <> destination_lng
  ),
  CONSTRAINT tr_fuel_cost_requires_truck CHECK (
    fuel_cost IS NULL OR truck_id IS NOT NULL
  ),
  CONSTRAINT tr_source_check CHECK (source IN ('internal', 'external'))
);

-- Índices
CREATE INDEX IF NOT EXISTS idx_tr_status     ON transport_requests (status);
CREATE INDEX IF NOT EXISTS idx_tr_truck_id   ON transport_requests (truck_id);
CREATE INDEX IF NOT EXISTS idx_tr_client_id  ON transport_requests (client_id);
CREATE INDEX IF NOT EXISTS idx_tr_created_at ON transport_requests (created_at DESC);

-- Tabla puente para asignar uno o varios camiones a una solicitud.
-- transport_requests.truck_id conserva el camion principal para compatibilidad.
CREATE TABLE IF NOT EXISTS transport_request_trucks (
  transport_request_id UUID NOT NULL
    REFERENCES transport_requests(id)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  truck_id UUID NOT NULL
    REFERENCES trucks(id)
    ON DELETE RESTRICT
    ON UPDATE CASCADE,
  sequence INTEGER NOT NULL,
  created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),

  CONSTRAINT trt_pk PRIMARY KEY (transport_request_id, truck_id),
  CONSTRAINT trt_sequence_positive CHECK (sequence > 0),
  CONSTRAINT trt_request_sequence_unique UNIQUE (transport_request_id, sequence)
);

CREATE INDEX IF NOT EXISTS idx_trt_truck_id ON transport_request_trucks (truck_id);

-- ─────────────────────────────────────────
-- TABLA: fuel_prices
-- Histórico de precios oficiales de combustible PETROPAR
-- ─────────────────────────────────────────

CREATE TABLE IF NOT EXISTS fuel_prices (
  id            UUID         PRIMARY KEY DEFAULT gen_random_uuid(),
  brand         VARCHAR(60)  NOT NULL DEFAULT 'Petropar',
  fuel_type     VARCHAR(40)  NOT NULL DEFAULT 'Diésel Común',
  product_name  VARCHAR(120) NOT NULL,
  price_pyg     INTEGER      NOT NULL,
  valid_from    DATE         NULL,
  source_url    TEXT         NOT NULL,
  scraped_at    TIMESTAMPTZ  NOT NULL DEFAULT NOW(),
  created_at    TIMESTAMPTZ  NOT NULL DEFAULT NOW(),

  CONSTRAINT fuel_prices_price_positive CHECK (price_pyg > 0),
  CONSTRAINT fuel_prices_unique_snapshot UNIQUE NULLS NOT DISTINCT (
    brand, fuel_type, price_pyg, valid_from, source_url
  )
);

CREATE INDEX IF NOT EXISTS idx_fuel_prices_product_valid
  ON fuel_prices (brand, fuel_type, valid_from DESC, scraped_at DESC);

DO $$ BEGIN
  ALTER TABLE transport_requests
    ADD CONSTRAINT tr_fuel_price_fk
    FOREIGN KEY (fuel_price_id) REFERENCES fuel_prices(id) ON DELETE RESTRICT;
EXCEPTION
  WHEN duplicate_object THEN NULL;
END $$;

-- ─────────────────────────────────────────
-- FUNCIÓN: auto-actualizar updated_at
-- ─────────────────────────────────────────

CREATE OR REPLACE FUNCTION trigger_set_updated_at()
RETURNS TRIGGER AS $$
BEGIN
  NEW.updated_at = NOW();
  RETURN NEW;
END;
$$ LANGUAGE plpgsql;

DROP TRIGGER IF EXISTS set_updated_at_trucks ON trucks;
CREATE TRIGGER set_updated_at_trucks
  BEFORE UPDATE ON trucks
  FOR EACH ROW EXECUTE FUNCTION trigger_set_updated_at();

DROP TRIGGER IF EXISTS set_updated_at_app_users ON app_users;
CREATE TRIGGER set_updated_at_app_users
  BEFORE UPDATE ON app_users
  FOR EACH ROW EXECUTE FUNCTION trigger_set_updated_at();

DROP TRIGGER IF EXISTS set_updated_at_clients ON clients;
CREATE TRIGGER set_updated_at_clients
  BEFORE UPDATE ON clients
  FOR EACH ROW EXECUTE FUNCTION trigger_set_updated_at();

DROP TRIGGER IF EXISTS set_updated_at_transport_requests ON transport_requests;
CREATE TRIGGER set_updated_at_transport_requests
  BEFORE UPDATE ON transport_requests
  FOR EACH ROW EXECUTE FUNCTION trigger_set_updated_at();

-- ─────────────────────────────────────────
-- DATOS SEMILLA — CAMIONES
-- ─────────────────────────────────────────

INSERT INTO trucks (id, license_plate, max_capacity, fuel_consumption_per_km, status)
VALUES
  ('a1b2c3d4-0001-0001-0001-000000000001', 'ABC-123', 30, 0.350, 'available'),
  ('a1b2c3d4-0002-0002-0002-000000000002', 'DEF-456', 20, 0.280, 'available'),
  ('a1b2c3d4-0003-0003-0003-000000000003', 'GHI-789', 50, 0.520, 'available'),
  ('a1b2c3d4-0004-0004-0004-000000000004', 'JKL-012', 15, 0.210, 'maintenance'),
  ('a1b2c3d4-0005-0005-0005-000000000005', 'MNO-345', 40, 0.430, 'available')
ON CONFLICT (license_plate) DO NOTHING;

INSERT INTO app_users (
  username, email, full_name, password_hash, superuser, active
)
VALUES (
  'admin',
  'admin@bovitrans.com.py',
  'Administrador BoviTrans',
  'pbkdf2_sha256$210000$1e46092fb492ec0a096f360a06973c50$23702de87173e4851b06c742aed5bdc2bac72ddf8e17ce536e592dca0d8e3e1b',
  TRUE,
  TRUE
)
ON CONFLICT (username) DO NOTHING;

INSERT INTO app_user_permissions (user_id, module_key)
SELECT id, module_key
FROM app_users
CROSS JOIN (VALUES ('logistics'), ('fleet'), ('users')) AS modules(module_key)
WHERE username = 'admin'
ON CONFLICT DO NOTHING;

-- ─────────────────────────────────────────
-- DATOS SEMILLA — SOLICITUDES DE TRANSPORTE
-- ─────────────────────────────────────────

INSERT INTO transport_requests (
  id, client_name, cattle_count,
  origin_name, origin_lat, origin_lng,
  destination_name, destination_lat, destination_lng,
  status, distance_km, fuel_cost, truck_id, trips_needed
)
VALUES
  (
    'b2c3d4e5-0001-0001-0001-000000000001',
    'Estancia Don Carlos',
    25,
    'Asunción, Paraguay',       -25.2867, -57.6470,
    'Encarnación, Paraguay',    -27.3364, -55.8675,
    'assigned',
    370.500,
    -- costo: 370.5 km * 0.35 L/km * 1.45 $/L = 187.83
    187.83,
    'a1b2c3d4-0001-0001-0001-000000000001',
    1
  ),
  (
    'b2c3d4e5-0002-0002-0002-000000000002',
    'Ganadería El Ombú',
    18,
    'Ciudad del Este, Paraguay', -25.5097, -54.6130,
    'Concepción, Paraguay',      -23.4065, -57.4343,
    'pending',
    NULL, NULL, NULL, 1
  ),
  (
    'b2c3d4e5-0003-0003-0003-000000000003',
    'Hacienda Los Pioneros',
    55,
    'Pilar, Paraguay',          -26.8590, -58.3030,
    'Pedro Juan Caballero, Paraguay', -22.5497, -55.7297,
    'pending',
    NULL, NULL, NULL, 2
  )
ON CONFLICT DO NOTHING;

INSERT INTO clients (
  company_name, business_name, document_number, document_type_id, phone_number,
  city_id
)
SELECT DISTINCT
  client_name,
  client_name,
  'PEND-' || SUBSTRING(MD5(client_name), 1, 8),
  1,
  'Sin registrar',
  1
FROM transport_requests
ON CONFLICT (document_type_id, document_number) DO NOTHING;

UPDATE transport_requests AS request
SET client_id = client.id
FROM clients AS client
WHERE request.client_id IS NULL
  AND client.business_name = request.client_name;

INSERT INTO transport_request_trucks (transport_request_id, truck_id, sequence)
SELECT id, truck_id, 1
FROM transport_requests
WHERE truck_id IS NOT NULL
ON CONFLICT DO NOTHING;

-- ─────────────────────────────────────────
-- Actualizar estado del camión asignado
-- ─────────────────────────────────────────

UPDATE trucks
SET status = 'assigned'
WHERE id = 'a1b2c3d4-0001-0001-0001-000000000001';
